% \VignetteEngine{knitr::knitr}
% \VignetteIndexEntry{drexplorer}
% \VignettePackage{drexplorer}

% \\mdadqsfs02\bioinfo2\ptong1\Projects\Coombes\IC50Package\Package\drexplorer\inst\doc
% \\mdadqsfs02\bioinfo2\ptong1\Projects\Coombes\IC50Package\Package\for_vignettes\drexplorer.Rnw
% To compile this document, run the commands within R

\documentclass[12pt]{article}
\usepackage[a4paper,left=3cm,top=2cm,bottom=3cm,right=3cm,ignoreheadfoot]{geometry}
\pagestyle{empty}
\usepackage[usenames,dvipsnames]{xcolor}
\usepackage{helvet}
\usepackage[titletoc]{appendix}
\usepackage{tocloft}

\setlength{\parindent}{0em}
\setlength{\parskip}{.5em}

\renewcommand{\familydefault}{\sfdefault}

\newcommand{\Rcode}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\small\texttt{#1}}}
\newcommand{\Rfunction}[1]{\Robject{#1}}
\newcommand{\Rpackage}[1]{\textit{#1}}
\newcommand{\Rparameter}[1]{\textit{#1}}
\newcommand{\Rclass}[1]{\textit{#1}}
\newcommand{\R}{\textsf{R}}

\usepackage[
  bookmarks,%
  colorlinks,%
  linktoc=section,%
  linkcolor=RedViolet,%
  citecolor=RedViolet,%
  urlcolor=RedViolet,%
  linkbordercolor={1 1 1},%
  citebordercolor={1 1 1},%
  urlbordercolor={1 1 1},%
  raiselinks,%
  plainpages,%
  pdftex
  ]{hyperref}


\usepackage{cite}
\renewcommand{\floatpagefraction}{0.9}

\usepackage{sectsty}
\sectionfont{\sffamily\bfseries\color{RoyalBlue}\sectionrule{0pt}{0pt}{-1ex}{1pt}}
\subsectionfont{\sffamily\bfseries\color{RoyalBlue}}
\subsubsectionfont{\sffamily\bfseries\color{RoyalBlue}}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead{}
\fancyfoot{}
\lfoot{}\cfoot{}\rfoot{}
\renewcommand{\headrule}{}

\usepackage{graphicx}
%\usepackage{xstring}


<<include=FALSE>>=
library(knitr)
library(drexplorer)
opts_chunk$set(tidy=TRUE,tidy.opts=list(keep.blank.line=FALSE, width.cutoff=50),out.truncate=80,out.lines=6,cache=FALSE,dev='pdf',include=TRUE,fig.width=6,fig.height=6,resolution=150)
@

\newcommand{\fixme}[1]{{\textbf{Fixme:} \textit{\textcolor{blue}{#1}}}}

\title{Dose-response Explorer: Exploring different models and drug-drug interaction} 
\author{Kevin R Coombes and Pan Tong}
\date{\today}

\begin{document}


\maketitle

\tableofcontents
%\listoffigures
%\listoftables

<<echo=FALSE>>=
options(digits=3, width=80, prompt=" ", continue=" ")
@ 

\section{Introduction}
There is a great variety of models developed for dose-response data, many of which have been implemented in 
 the \Rpackage{drc} and \Rpackage{DoseFinding} packages. \Rpackage{drexplorer} combines both packages to aid the user to visually examine and compare how existing models
 perform on the data. We also incorporate model selection. Another important feature for \Rpackage{drexplorer} is to allow the user to identify outlier measurements and visually examine
 how these outliers affect the fitted model. 

 In addition to fit dose-response models, \Rpackage{drexplorer} also implements methods previously published to assess drug-drug interaction. 
 Graphical User Interfaces (GUIs) have been
designed to allow users without advanced programming skills to perform dose-response analysis.  

 The main entry for \Rpackage{drexplorer} is the drFit() function and computeIC() function. drFit() fits a model.
Outlier detection is also embedded into drFit(). Once a model is fitted, computeIC() computes IC values at specified percentiles.

\section{Outlier identification}
This package implements the method by Newman, D. The test statistic q=w/s where w is the range of the data and s is sample standard deviation
estimated from controls. The null distribution for q has been derived and 1\% and 5\% quantiles have been given in the paper.

We implement this procedure. In particular, NewmanTest() returns a logic vector specifying whether the observations are outliers.
Usually, drug-response data contains multiple doses. Therefore, we write a wrapper drOutlier() that compute the result for all doses each dose at a time.

We use the \texttt{ryegrass} data from \Rpackage{drc} package for illustration purpose.

First, we load the \Rpackage{drexplorer} package and attach the \Rpackage{ryegrass} data.
<<loadLibrary>>=
library(drexplorer)
data(ryegrass)
@ 

At dose=3.75 and significance level 0.05, we find there is one outlier identified:
<<>>=
dose <- ryegrass[, 2]
response <- ryegrass[, 1]
## potential outlier at dose 3.75
NewmanTest(ref=response[dose==0], obs=response[dose==3.75], alpha=0.05)
@

We also examine all dose levels and find no further outliers:

<<>>=
drOutlier(drMat=ryegrass[, c(2, 1)], alpha=0.05)
@

\section{Assessing Reproducibility}
Sometimes replicated viability assays are performed. In such case, it is useful to examine if the experiments are reproducible. 
A good metric is the Concordance Correlation Coefficient (CCC) that captures both the location shift as
 well as scale shift between the replicates. The plotCCC function can be used to compute CCC and visualize the replicated data.
 

<<>>=
set.seed(100)
r1 <- runif(28)
r2 <- r1+rnorm(28, 0, 0.1)
ccc <- plotCCC(r1, r2)
ccc
@ 

Here we simulate two response vectors and calculate CCC. The computed CCC value is \Sexpr{round(ccc['ccc'], 3)}, location shift is
\Sexpr{round(ccc['l_shift'], 3)}, scale shift is \Sexpr{round(ccc['s_shift'], 3)}, Pearson correlation is \Sexpr{round(ccc['corr'], 3)}. 

\section{Fit dose-response models}
Below we show how to fit a dose-response model. The fitDRC() function is a wrapper to the \Rpackage{drc} and \Rpackage{DoseFinding} packages.
Therefore, all models implemented by either package can be fitted. A model is specified by a modelName and package name to be passed to this function.

Outliers can be identified and removed from model fitting by specifying the parameter alpha (either at significance level of 0.01 or 0.05). To disable outlier
identification, set alpha=1.

To remove controls (responses at dose=0) during model fitting, we can set fitCtr=FALSE.

Note that the responses are scaled by mean response at dose=0 before model fitting. 

Below we fit a sigmaEmax model. We set alpha=1 to disable outlier removal and fitCtr=FALSE to exclude controls.
<<>>=
fit_sigEmax_alpha1 <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "sigEmax", 
	alpha=1, fitCtr=FALSE)
@

The result is slightly different when outliers passing significance level of 0.05 is removed.
<<>>=
fit_sigEmax_alpha_o5 <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "sigEmax", 
	alpha=0.05, fitCtr=FALSE)
fit_sigEmax_alpha1@fit
fit_sigEmax_alpha_o5@fit
@

\section{Predict response}
One a model is fitted, it can be used to make predictions.

Below we make predictions at the observed dose levels with a previously fitted model. Since the responses are scaled by mean response at dose=0 in model fitting,
the predicted responses are also scaled by the mean response from controls. By default, the predict function makes predictions at observed doses.

<<>>=
y <- predict(fit_sigEmax_alpha_o5)
y
@

\section{Obtain IC values}
We implement two approaches for IC value computation. One is to interpolate the observed dosages and try to use the dose that has the predicted response closest to the 
specified percentile of IC value. The second approach is to use root finding by setting the fitted model to equal to the specified percentile. In most cases, the result
are similar. However, the latter approach may give IC50 values beyond observed dosages and sometimes not robust. The computeIC() function implements both approaches. By setting
interpolation=TRUE (the default value) in the computeIC() function, the interpolation approach will be selected.   

Computing IC values at different quantiles is also easy. Similar to the fitDRC() function, different models as well as other options (alpha and fitCtr) 
can be specified in estimating IC value. 

Below we estimate IC50 at different percentiles with the sigmoid Emax model with outlier removal (alpha=0.05) fitted previously. We see that 
estimates from interpolation and prediction by the model are quite similar. 
<<>>=
computeIC(fit_sigEmax_alpha_o5, percent=seq(0, 1, by=0.1), log.d=FALSE, interpolation=TRUE)
computeIC(fit_sigEmax_alpha_o5, percent=seq(0, 1, by=0.1), log.d=FALSE, interpolation=FALSE)
@

\section{Comparing multiple dose-response curves}
We provide S4 generic functions (plot and lines) for fitted model. As a result, it is easy to compare different models 
and graphically examine outliers through multiple dose-response curves.

Outliers at significance levels 0.01 and 0.05 are indicated by different colors and symbols. Below we show the LL.3, LL.3u and sigEmax curves in this example
corresponding to the three-parameter log-logistic model with lower limit 0, three-parameter log-logistic with upper limit 1 and the sigmoid Emax model.

<<>>=
fit.LL.3 <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "LL.3", alpha=0.05, fitCtr=FALSE)
fit.LL.3u <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "LL.3u", alpha=0.05, fitCtr=FALSE)
fit.sigEmax <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "sigEmax", alpha=0.05, fitCtr=FALSE)
###
plot(fit.LL.3, main='', col=4, lwd=2)
lines(fit.LL.3u, col=5, lwd=2)
lines(fit.sigEmax, col=6, lwd=2)
legend("bottomleft", c('LL.3', 'LL.3u', 'sigEmax'), col=4:6, lwd=3)
@

With these many models fitted, which one should be preferred? One way is to look at the Residual Standard Error (RSE) as below.
We see that the LL.3u model is best by the RSE criteria.

<<>>=
sapply(list(fit.LL.3, fit.LL.3u, fit.sigEmax), function(x) x@info$RSE)
@

We also compare the curve using sigEmax model with and without outlier identification.

<<>>=
# no outlier excluded
fit.sigEmax0 <- drFit(drMat=ryegrass[, c(2, 1)], modelName = "sigEmax", alpha=1, fitCtr=FALSE)
###
plot(fit.sigEmax0, main='sigEmax model', col=7, lwd=2)
lines(fit.sigEmax, col=6, lwd=2)
legend("bottomleft", c('alpha=0.05', 'ignored'), col=c(6, 7), lwd=3)
@

\section{Drug Interaction Index}
Administering two drugs simultaneously might induce stronger effect than if administered
separately. This is called synergism. Experiments to detect synergism (or antagonism which is the opposite) are usually in two forms. 
One is the fixed ratio design (ray design) where the ratio of doses between 
two drugs is a constant. Another one is grid design which means all-possible combinations of drug doses
are available. 

Two papers have been published regarding to drug interaction index (IAI) by Lee et al, 
	one in 2007 (Lee2007) \cite{lee2007interaction} and on in 2009 (Lee2009) \cite{lee2009confidence}. The Lee2007 paper 
described five methods to assess interaction: (1) Lowewe additivity model using interaction index (IAI) (2) Model of Greco et al 1990.
This approach uses $\alpha$ as the metric and it can be related to IAI (3) Model of Machado and Robinson which uses a metric denoted
as $\eta$ (4) Model of Plummer and Short which can also be linked to IAI through the parameter $\beta_4$ (5) Model of
Carter et al that can be linked to IAI through the parameter $\beta_{12}$. For more details 
of these models, please refer to Lee2007 \cite{lee2007interaction}.

The two papers by Lee et al discussed the fixed ratio design and the source code for doing this is incorporated
into \Rpackage{drexplorer}. To work on grid design, a fixed ratio from the data needs to be selected in order to apply their method. For
example, the Lee2007 paper provided an example of grid design. A fixed ratio of 1 was specified in the paper. The specification of
fixed ratio would affect the fitted median effect model (see definition in \cite{lee2007interaction}) for the drug mixture as well as
estimation of IAI. As a result, IAI has a ratio dependent interpretation. 

Below we load the UMSCC22B data from \cite{lee2009confidence}. This data has a fixed ratio design. The \texttt{fitIAI} function estimates IAI
as well as its confidence interval after specifying dose1, dose2 and effect (between 0 and 1). 

<<>>=
data(UMSCC22B)	
fit_fixedRay <- fitIAI(d1=UMSCC22B[, 1], d2=UMSCC22B[, 2], 
			e=UMSCC22B[, 3], name1='SCH66336', name2='4HPR')
@

The \texttt{plotIAI} function is then used to generate different plots including IAI versus response, IAI versus dose (predicted dose for the
drug mixture, see equation (6) in \cite{lee2007interaction}), median effect plot and dose response curves. We can also plot IAI versus response as well as IAI versus
dose in one figure by specifying mode='both'. 

The median effect equation \cite{chou1984quantitative} is as following:
$$E=\frac{(d/D_{m})^m}{1+(d/D_{m})^m}$$
where E is the induced effect of a drug with dose d whose median effective dose is $D_{m}$ and $m$ is a slope parameter. 

This equation can be arranged as:
$$logit(E)=m(log d - log D_{m})$$

The median effect plot is just plotting logit(E) versus log10 dose; The dose response curve is plotting E versus dose. 

<<>>=
# IAI vs response
plotIAI(fit_fixedRay, type='IAI', mode='response') 
@

<<>>=
# IAI versus dose
plotIAI(fit_fixedRay, type='IAI', mode='dose') 
@

<<>>=
# median effect
plotIAI(fit_fixedRay, type='medianEffect') 
@

In \cite{lee2007interaction}, there is an example data (nl22B2) using grid design. Here we examine the estimate of IAI at different fixed ratios.

<<>>=
data(nl22B2)	
fit_allPoss_1 <- fitIAI(d1=nl22B2$schd, d2=nl22B2$hpr, e=nl22B2$y1, name1='SCH66336', name2='4HPR',d2.d1.force=1)
fit_allPoss_2 <- fitIAI(d1=nl22B2$schd, d2=nl22B2$hpr, e=nl22B2$y1, name1='SCH66336', name2='4HPR',d2.d1.force=2)
@

From the median effect plot, we can find that there are 4 data points for drug mixtures at fixed ratio of 1 while only 2 data points
are available at fixed ratio of 2.

<<>>=
# median effect
plotIAI(fit_allPoss_1, type='medianEffect') 
@

<<>>=
plotIAI(fit_allPoss_2, type='medianEffect') 
@

Below we compare IAI estimated from the two scenarios. 

<<>>=
plotCCC(fit_allPoss_1$CI$IAI, fit_allPoss_2$CI$IAI)
@



% for MacSynergism II
% write.csv(dcast(nl22B2, schd~hpr), 'n122B2_wide_format.csv')

\section{GUI Usage}
GUI interface has been shipped with \Rpackage{drexplorer} which is built upon the \Rpackage{fgui}. After loading the \Rpackage{drexplorer} 
package, typing $$\texttt{drexplorerGUI\_1()}$$ in the R console will bring out the GUI for fitting dose-response curves. 
Similarly,  typing $$\texttt{drexplorerGUI\_2()}$$ will bring out the GUI for drug-drug interaction analysis. In both case, example
data sets have been attached. 

\section{Session Info}
<<sessInfo, results='asis', echo=FALSE>>=
toLatex(sessionInfo())
@

%   cd /data/bioinfo2/ptong1/Projects/Coombes/IC50Package/Package/for_vignettes; R0
%   knitr::knit2pdf("drexplorer.Rnw")
%   knitr::knit("drexplorer.Rnw")

\bibliographystyle{unsrt}
\bibliography{drexplorer}

\end{document}
